# Generated by Django 5.2.11 on 2026-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('clasificacion', models.CharField(choices=[('consumo', 'Consumo'), ('venta', 'Venta'), ('factura', 'En Factura de Servicio')], max_length=20, verbose_name='Clasificación')),
                ('no_contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Contrato')),
            ],
            options={
                'verbose_name': 'Catálogo de Cliente',
                'verbose_name_plural': 'Catálogo de Clientes',
                'ordering': ['cliente'],
            },
        ),
    ]
