# Generated by Django 5.2.11 on 2026-08-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0002_transporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporte',
            options={'ordering': ['cliente', 'tipo_vehiculo'], 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.AddField(
            model_name='transporte',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='combustible.catalogocliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
