# Generated by Django 5.2.11 on 2026-08-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0003_alter_transporte_options_transporte_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente a Revisión'), ('aprobada', 'Aprobada por el Director'), ('rechazada', 'Rechazada por el Director')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Consumo')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Venta')),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total General')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_2', models.BooleanField(default=False, verbose_name='Anexo 2')),
                ('cant_abastecer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cant. a Abastecer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.catalogocliente', verbose_name='Cliente')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='combustible.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
            },
        ),
    ]
