# Generated by Django 5.2.11 on 2026-08-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0004_solicitud_detallesolicitud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud',
            new_name='ModeloSolicitud',
        ),
        migrations.AlterModelOptions(
            name='modelosolicitud',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Modelo de Solicitud', 'verbose_name_plural': 'Modelos de Solicitudes'},
        ),
    ]
