# Generated by Django 5.2.11 on 2026-08-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0005_rename_solicitud_modelosolicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSolicitudVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100, verbose_name='Actividad')),
                ('cant_abastecer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cant. a Abastecer')),
                ('detalle_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='combustible.detallesolicitud')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud - Vehículo',
                'verbose_name_plural': 'Detalles de Solicitudes - Vehículos',
            },
        ),
    ]
