# Generated by Django 5.2.11 on 2026-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0006_detallesolicitudvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelosolicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del Rechazo'),
        ),
    ]
