# Generated by Django 5.2.11 on 2026-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0007_modelosolicitud_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad Actual de Combustible')),
            ],
            options={
                'verbose_name': 'Almacén de Producción',
                'verbose_name_plural': 'Almacén de Producción',
            },
        ),
        migrations.CreateModel(
            name='SuministroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad a Insertar')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Nota')),
                ('cantidad_antes', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad Antes de Insertar')),
                ('cantidad_despues', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad Después de Insertar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente a Validar'), ('validado', 'Validado')], default='pendiente', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Suministro de Combustible',
                'verbose_name_plural': 'Suministros de Combustible',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
