# Generated by Django 5.2.11 on 2026-08-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0008_almacenproduccion_suministrocombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelosolicitud',
            name='transferida',
            field=models.BooleanField(default=False, verbose_name='Transferida a Aseguramiento'),
        ),
    ]
