# Generated by Django 5.2.11 on 2026-08-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0009_modelosolicitud_transferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelosolicitud',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo Final'),
        ),
        migrations.AddField(
            model_name='modelosolicitud',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo Inicial'),
        ),
    ]
