# Generated by Django 5.2.11 on 2026-08-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0010_modelosolicitud_saldo_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenAseguramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad Actual de Combustible')),
            ],
            options={
                'verbose_name': 'Almacén de Aseguramiento',
                'verbose_name_plural': 'Almacén de Aseguramiento',
            },
        ),
        migrations.RemoveField(
            model_name='modelosolicitud',
            name='saldo_final',
        ),
        migrations.RemoveField(
            model_name='modelosolicitud',
            name='saldo_inicial',
        ),
        migrations.RemoveField(
            model_name='modelosolicitud',
            name='transferida',
        ),
        migrations.CreateModel(
            name='TransferenciaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Transferencia')),
                ('saldo_aseguramiento', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo en Almacén de Aseguramiento')),
                ('cantidad_transferida', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transferencia')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('transferido', 'Transferido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia', to='combustible.modelosolicitud', verbose_name='Solicitud Aprobada')),
            ],
            options={
                'verbose_name': 'Transferencia entre Almacenes',
                'verbose_name_plural': 'Transferencias entre Almacenes',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
