# Generated by Django 5.2.11 on 2026-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0011_almacenaseguramiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionAlmacenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Existencia')),
                ('entrada_factura', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Entrada por Factura')),
                ('generacion', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Generación')),
                ('transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Transferencia')),
                ('nueva_existencia', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nueva Existencia')),
            ],
            options={
                'verbose_name': 'Operación de Almacén de Producción',
                'verbose_name_plural': 'Operaciones de Almacén de Producción',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
