# Generated by Django 5.2.11 on 2026-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0012_operacionalmacenproduccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuministroCombustible',
        ),
        migrations.AddField(
            model_name='operacionalmacenproduccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
