# Generated by Django 5.2.11 on 2026-08-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0013_delete_suministrocombustible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAlmacenAseguramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('cantidad_total_aprobada', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad Total Aprobada')),
                ('despacho_real_total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Despacho Real Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('despachado', 'Despachado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aseguramiento', to='combustible.modelosolicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Registro de Almacén de Aseguramiento',
                'verbose_name_plural': 'Registros de Almacén de Aseguramiento',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DespachoRealVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho_real', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despacho Real')),
                ('detalle_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.detallesolicitudvehiculo', verbose_name='Vehículo de Solicitud')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='combustible.registroalmacenaseguramiento', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Despacho Real por Vehículo',
                'verbose_name_plural': 'Despachos Reales por Vehículos',
            },
        ),
    ]
