# Generated by Django 5.2.11 on 2026-08-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0014_registroalmacenaseguramiento_despachorealvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroalmacenaseguramiento',
            name='total_consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total de Consumo Sobrante'),
        ),
        migrations.AddField(
            model_name='registroalmacenaseguramiento',
            name='total_existente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Existente'),
        ),
        migrations.AddField(
            model_name='registroalmacenaseguramiento',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total de Venta Sobrante'),
        ),
        migrations.CreateModel(
            name='ResultadoAlmacenAseguramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('total_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total de Consumo')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total de Venta')),
                ('total_existente', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Existente')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='combustible.registroalmacenaseguramiento', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Resultado de Almacén de Aseguramiento',
                'verbose_name_plural': 'Resultados de Almacén de Aseguramiento',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
