# Generated by Django 5.2.11 on 2026-08-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0015_registroalmacenaseguramiento_total_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoalmacenaseguramiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resultadoalmacenaseguramiento',
            name='registro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='combustible.registroalmacenaseguramiento', verbose_name='Registro'),
        ),
    ]
