# Generated by Django 5.2.11 on 2026-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0016_resultadoalmacenaseguramiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoalmacenaseguramiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
