# Generated by Django 5.2.11 on 2026-08-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0017_resultadoalmacenaseguramiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroalmacenaseguramiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('borrador', 'Borrador'), ('despachado', 'Despachado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
