# Generated by Django 5.2.11 on 2026-09-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0018_alter_registroalmacenaseguramiento_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroalmacenaseguramiento',
            options={'ordering': ['-id'], 'verbose_name': 'Registro de Almacén de Aseguramiento', 'verbose_name_plural': 'Registros de Almacén de Aseguramiento'},
        ),
        migrations.AlterField(
            model_name='registroalmacenaseguramiento',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora'),
        ),
    ]
