# Generated by Django 5.2.11 on 2026-09-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0019_alter_registroalmacenaseguramiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocliente',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
