# Generated by Django 5.2.11 on 2026-09-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0020_catalogocliente_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenaseguramiento',
            name='cantidad_actual',
        ),
        migrations.RemoveField(
            model_name='transferenciaalmacen',
            name='saldo_aseguramiento',
        ),
        migrations.AddField(
            model_name='almacenaseguramiento',
            name='cantidad_consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad de Consumo'),
        ),
        migrations.AddField(
            model_name='almacenaseguramiento',
            name='cantidad_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad de Venta'),
        ),
        migrations.AddField(
            model_name='transferenciaalmacen',
            name='cantidad_consumo_transferida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transferencia de Consumo'),
        ),
        migrations.AddField(
            model_name='transferenciaalmacen',
            name='cantidad_venta_transferida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transferencia de Venta'),
        ),
        migrations.AddField(
            model_name='transferenciaalmacen',
            name='saldo_consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo de Consumo en Aseguramiento'),
        ),
        migrations.AddField(
            model_name='transferenciaalmacen',
            name='saldo_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo de Venta en Aseguramiento'),
        ),
        migrations.AlterField(
            model_name='transferenciaalmacen',
            name='cantidad_transferida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transferencia Total'),
        ),
    ]
