# Generated by Django 5.2.11 on 2026-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0021_remove_almacenaseguramiento_cantidad_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciaalmacen',
            name='cantidad_consumo_transferida',
        ),
        migrations.RemoveField(
            model_name='transferenciaalmacen',
            name='cantidad_venta_transferida',
        ),
        migrations.RemoveField(
            model_name='transferenciaalmacen',
            name='saldo_consumo',
        ),
        migrations.RemoveField(
            model_name='transferenciaalmacen',
            name='saldo_venta',
        ),
        migrations.AddField(
            model_name='transferenciaalmacen',
            name='saldo_aseguramiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo en Almacén de Aseguramiento'),
        ),
        migrations.AlterField(
            model_name='transferenciaalmacen',
            name='cantidad_transferida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transferencia'),
        ),
    ]
