# Generated by Django 5.2.11 on 2026-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0023_alter_almacenproduccion_cantidad_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenproduccion',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad Actual de Combustible'),
        ),
    ]
