# Generated by Django 5.2.11 on 2026-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('admin', 'Administrador del Sistema'), ('transporte', 'Departamento de Transporte'), ('petroleo', 'Departamento de Petróleo'), ('almacen', 'Almacén'), ('director', 'Director General'), ('director_aseguramiento', 'Director de Aseguramiento'), ('director_contabilidad', 'Director de Contab. y Finanzas'), ('director_produccion', 'Director de Producción')], default='transporte', max_length=30, verbose_name='Departamento / Rol'),
        ),
    ]
